### ISSUE TITLE
_shadowLayers is always null?

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/Supertool2-Simplify#1]
No shadowLayers, no selection, nothing happens. :-( @schriftgestalt

**Comment by schriftgestalt** [comment]
Can you give more details?

**Comment by simoncozens** [comment]
I'm not sure what is expected to set the `_shadowLayers` variable. It looks like from the template that this is supposed to be set by Glyphs and then the filter operates on those layers:

https://github.com/schriftgestalt/GlyphsSDK/blob/c06bedb5b34dc61ba2401f369a450e4e8bf3a0f9/Xcode%20Templates/Glyphs%20Dev/Glyphs%20Filter%20Plugin.xctemplate/___PACKAGENAMEASIDENTIFIER___.m#L95-L97

So I did the same:

https://github.com/simoncozens/Supertool2-Simplify/blob/6f0c7975146aa0e20cea3b2d1b49f3fff507cc20/SuperTool2-Simplify/SuperTool2_Simplify.m#L174-L178

But I always get `Processing (null)`. I've tried selecting paths, selecting layers, etc. but still nothing.

**Comment by schriftgestalt** [comment]
this stuff is set by the `GSFilterPlugin` class:
```
- (NSError *)setup {
	_shadowLayers = [[NSMutableArray alloc] init];
	for (GSLayer *currLayer in _layers) {
		[currLayer.parent.undoManager disableUndoRegistration];
		GSLayer *shadowLayer = [currLayer copy];
		[currLayer stopUpdates];
		[shadowLayer stopUpdates];
		[currLayer saveHints];
		[shadowLayer saveHints];
		NSArray *shapesCopy = shadowLayer.shapes;
		NSDictionary *anchorsCopy = shadowLayer.anchors;
		NSMutableOrderedSet *selectionCopy = shadowLayer.selection;
		shadowLayer.shapes = currLayer.shapes;
		shadowLayer.anchors = currLayer.anchors;
		shadowLayer.selection = currLayer.selection;

		currLayer.shapes = shapesCopy;
		currLayer.anchors = anchorsCopy;
		currLayer.selection = selectionCopy;

		[_shadowLayers addObject:shadowLayer];
		[currLayer startUpdates];
		[shadowLayer startUpdates];
	}
	return nil;
}
```

**Comment by simoncozens** [comment]
...which I overrode and didn't call the superclass for. It works now, thanks!
